"""The pages of the site, for the plugins.

The generator gives the structure of the site (one entry per page, in order,
as written in structure/structure.yaml) in meta['structure'], and the pages
it generates in meta['built']: all of them, or those named by --only (the
other pages of the site are those of the previous build). A plugin working
on the pages (templates, HTML) uses built_pages; one writing a file for the
whole site (menu, redirection) uses structure.
"""

import json


def load_structure(site_directory):
    """The structure exported in a site directory (structure.json)."""
    with open(site_directory + '/structure/structure.json', encoding='utf-8') as fid:
        return json.load(fid)


def structure(meta):
    """All the pages of the site, in order."""
    if 'structure' not in meta:
        meta['structure'] = load_structure(meta['site_directory'])
    return meta['structure']


def built_pages(meta):
    """The pages generated by this build."""
    return meta['built'] if 'built' in meta else structure(meta)


def template_path(meta, entry):
    """Template of a page of the structure in the site (before rendering)."""
    return meta['site_directory'] + entry['template']
