"""Style profile of a corpus of slide decks: what the slides of an author
usually look like, and how they are written.

    python tools/style_profile.py DECK [DECK ...] --output style/

DECK is the directory of a slide project generated by static_website_lhtml:
it contains src/<chapter>/ (LHTML sources) and _site/<chapter>/html/ (the
generated pages, with structure/structure.yaml). The generated pages are
measured as they are (nothing is regenerated), in headless Chrome
(plugins/assets/layout_measure.js, requires `npm install`). Measurements are
cached in <output>/pages/ and only redone for pages generated since.

Output, for an LLM writing new slides in the same style:

    style.md          usual values of each deck (title, columns, fonts,
                      density), layout types of the slides with their
                      frequency, typical measures and examples (source and
                      thumbnail), and the LHTML idioms used in the sources
    style.json        the same data, for scripts
    types/<type>.png  thumbnails of examples of each layout type
"""

import argparse
import hashlib
import json
import os
import re
import subprocess
import sys
import tempfile
from collections import Counter

import yaml

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
sys.path.insert(0, ROOT)
sys.path.insert(0, os.path.join(ROOT, 'plugins'))

import layout_report as lr  # noqa: E402

MEASURE_JS = os.path.join(ROOT, 'plugins', 'assets', 'layout_measure.js')
CONTACT_JS = os.path.join(ROOT, 'plugins', 'assets', 'layout_contact.js')


# ---------------------------------------------------------------------------
# Pages of a corpus
# ---------------------------------------------------------------------------

def deck_pages(deck_dir):
    """Pages of a slide project: [{deck, chapter, dir, html, source}] in deck order."""
    deck = os.path.basename(os.path.normpath(deck_dir))
    site = os.path.join(deck_dir, '_site')
    pages = []
    for chapter in sorted(os.listdir(site)):
        structure = os.path.join(site, chapter, 'html', 'structure', 'structure.yaml')
        if not os.path.isfile(structure):
            continue
        with open(structure) as fid:
            entries = yaml.safe_load(fid) or []
        for e in entries:
            html = os.path.join(site, chapter, 'html', e['dir'] + e['filename'])
            if os.path.isfile(html):
                pages.append({'deck': deck, 'chapter': chapter, 'dir': e['dir'].rstrip('/'),
                              'html': os.path.abspath(html),
                              'source': os.path.abspath(os.path.join(deck_dir, 'src', chapter,
                                                                     e['dir'] + e['filename'] + '.j2'))})
    return pages


def page_key(page):
    return '/'.join(x for x in (page['deck'], page['chapter'], page['dir']) if x)


# ---------------------------------------------------------------------------
# Measurement (cached)
# ---------------------------------------------------------------------------

def measure(pages, output_dir, jobs=3, force=False, log=print):
    """Measure the pages not measured since they were generated, with `jobs`
    browsers in parallel. Sets page['out'] and page['layout_path']."""
    todo = []
    for p in pages:
        p['out'] = os.path.abspath(os.path.join(output_dir, 'pages', page_key(p)))
        p['layout_path'] = os.path.join(p['out'], 'layout.json')
        if force or not os.path.isfile(p['layout_path']) \
                or os.path.getmtime(p['layout_path']) < os.path.getmtime(p['html']):
            todo.append(p)
    log(f'{len(pages)} pages, {len(todo)} to measure')
    if not todo:
        return
    chunks = [todo[i::jobs] for i in range(jobs) if todo[i::jobs]]
    procs, files = [], []
    for chunk in chunks:
        with tempfile.NamedTemporaryFile('w', suffix='.json', delete=False) as fid:
            json.dump([{'html': p['html'], 'out': p['out']} for p in chunk], fid)
        files.append(fid.name)
        procs.append(subprocess.Popen(['node', MEASURE_JS, f'--input={fid.name}', '--images=render'],
                                      stderr=subprocess.PIPE, text=True))
    for proc, name in zip(procs, files):
        _, err = proc.communicate()
        os.remove(name)
        for line in err.splitlines():
            if line.startswith('layout_measure:'):
                log(line)


# ---------------------------------------------------------------------------
# Layout types
# ---------------------------------------------------------------------------

TYPES = {
    'section': 'section or title slide: no page title, a few words in large type',
    'media': 'page title + large figure(s) or video, almost no text',
    'media_row': 'page title + a row of 3 or more figures, little text',
    'columns': '2 or more columns of the same kind side by side (e.g. comparison: figure + caption in each)',
    'text_left_media_right': 'text on the left, figure(s) on the right',
    'media_left_text_right': 'figure(s) on the left, text on the right',
    'text_then_media': 'text, then figure(s) below',
    'media_then_text': 'figure(s), then text below',
    'text_code': 'text and code',
    'code_media': 'code and figure(s)',
    'code': 'mostly code',
    'text': 'text only (lists, formulas)',
    'other': 'none of the above',
}


def _union(rects):
    if not rects:
        return None
    return (min(r[0] for r in rects), min(r[1] for r in rects), max(r[2] for r in rects), max(r[3] for r in rects))


def _surface(rects):
    return sum((r[2] - r[0]) * (r[3] - r[1]) for r in rects)


def slide_features(layout):
    """Content of a slide (page title excluded) as text, code and media
    regions: their bounding boxes, the fraction of the area they cover, and
    counts (words, formulas, lines of code, media items)."""
    blocks = lr._visible(layout['blocks'])
    area = layout['area']
    surface = max(area['w'] * area['h'], 1)
    title = lr.page_title(blocks)
    content = blocks[1:] if title else blocks
    text, code, media = [], [], []
    media_items, fixed_media, fonts = [], 0, []
    for b in content:
        stats = b.get('text') or {}
        is_code = b['kind'] == 'code' or stats.get('code_lines', 0) > 0 and not stats.get('words')
        parts = lr._align_parts(b)
        for r in parts:
            if r[4] in ('media', 'trimmed'):
                media.append(r[:4])
            elif is_code:
                code.append(r[:4])
            elif r[4] == 'text':
                text.append(r[:4])
        boxes = [r[:4] for r in parts if r[4] in ('media', 'trimmed')]
        media_items += boxes
        if boxes and b.get('position') in ('fixed', 'absolute'):
            fixed_media += len(boxes)
        if stats.get('words'):
            fonts.append(b['font_size'])
    d = lr.density(content, area)
    return {
        'title': lr._tag(title) + f" {title['font_size']}px" if title else None,
        'words': d['words'], 'formulas': d['formulas'], 'code_lines': d['code_lines'], 'items': d['items'],
        'max_font': max(fonts) if fonts else None,
        'text_box': _union(text), 'code_box': _union(code), 'media_box': _union(media),
        'text_area': round(_surface(text) / surface, 3), 'code_area': round(_surface(code) / surface, 3),
        'media_area': round(_surface(media) / surface, 3),
        'media_items': len(media_items), 'fixed_media': fixed_media,
        'media_row': _row_size(media_items),
        'bands': _bands(text, code, media, area),
    }


def _bands(text, code, media, area, min_gap=40):
    """Columns of the content: the content is projected on the x axis
    (ignoring lines wider than half the area, such as a sentence above
    columns) and cut at the empty gaps of at least min_gap px. Returns, for
    each column, its x range and its dominant content: 'text', 'media' or
    'mixed' (both, e.g. a figure and its caption)."""
    typed = [(r, 'text') for r in text + code] + [(r, 'media') for r in media]
    typed = [(r, t) for r, t in typed if r[2] - r[0] <= 0.5 * area['w']]
    if not typed:
        return []
    intervals = sorted((r[0], r[2]) for r, _ in typed)
    bands = [list(intervals[0])]
    for x0, x1 in intervals[1:]:
        if x0 - bands[-1][1] < min_gap:
            bands[-1][1] = max(bands[-1][1], x1)
        else:
            bands.append([x0, x1])
    result = []
    for x0, x1 in bands:
        inside = [(r, t) for r, t in typed if r[0] >= x0 and r[2] <= x1]
        t_area = _surface([r for r, t in inside if t == 'text'])
        m_area = _surface([r for r, t in inside if t == 'media'])
        if t_area + m_area < 0.003 * area['w'] * area['h']:
            continue        # a stray label
        kind = 'mixed' if min(t_area, m_area) > 0.15 * (t_area + m_area) else ('media' if m_area > t_area else 'text')
        result.append({'x0': x0, 'x1': x1, 'kind': kind})
    return result


def _row_size(boxes):
    """Largest number of boxes side by side on a same line."""
    best = 0
    for b in boxes:
        row = [c for c in boxes if min(b[3], c[3]) - max(b[1], c[1]) > 0.5 * min(b[3] - b[1], c[3] - c[1])]
        best = max(best, len(row))
    return best


def classify(f, area):
    """Layout type of a slide (see TYPES) from its features."""
    words, text_box, media_box = f['words'], f['text_box'], f['media_box']
    has_code = f['code_lines'] >= 3 or f['code_area'] > 0.03
    has_media = f['media_area'] > 0.02
    if f['title'] is None and words <= 25 and not has_code and (f['max_font'] or 0) >= 40:
        return 'section'
    if has_code:
        if has_media:
            return 'code_media'
        return 'text_code' if words > 15 else 'code'
    if not has_media:
        return 'text' if words else 'other'
    bands = f['bands']
    if len(bands) >= 2:
        kinds = [b['kind'] for b in bands]
        if len(set(kinds)) == 1 or kinds.count('mixed') >= 2:
            return 'media_row' if kinds[0] == 'media' and len(bands) >= 3 and words <= 40 else 'columns'
        if kinds[0] == 'text' and kinds[-1] in ('media', 'mixed'):
            return 'text_left_media_right'
        if kinds[0] in ('media', 'mixed') and kinds[-1] == 'text':
            return 'media_left_text_right'
    if f['media_row'] >= 3 and words <= 40:
        return 'media_row'
    if words <= 15 or text_box is None:
        return 'media'
    tcx, mcx = (text_box[0] + text_box[2]) / 2, (media_box[0] + media_box[2]) / 2
    overlap_y = min(text_box[3], media_box[3]) - max(text_box[1], media_box[1])
    side_by_side = overlap_y > 0.3 * min(text_box[3] - text_box[1], media_box[3] - media_box[1])
    if side_by_side and abs(mcx - tcx) > 0.2 * area['w']:
        return 'text_left_media_right' if mcx > tcx else 'media_left_text_right'
    return 'text_then_media' if (media_box[1] + media_box[3]) > (text_box[1] + text_box[3]) else 'media_then_text'


# ---------------------------------------------------------------------------
# Idioms of the LHTML sources
# ---------------------------------------------------------------------------

OPENER = re.compile(r'^\s*([a-zA-Z_][\w-]*)?::')
STYLE = re.compile(r'\[([^\[\]\n]*:[^\[\]\n]*)\]')
CODE_OPENER = re.compile(r'^code::\[[^\]]*\]\s*$')
SPACER = re.compile(r'^\s*(?:div)?::\[\s*height:\s*([^;\]]+);?\s*\]::\s*$')


def source_idioms(paths):
    """Frequencies of the constructs used in the LHTML sources."""
    openers, tags, props, values, spacers, starts, classes = (Counter() for _ in range(7))
    n_lines, inline_math, display_math = [], 0, 0
    for path in paths:
        try:
            with open(path, encoding='utf-8', errors='replace') as fid:
                source = fid.read()
        except OSError:
            continue
        lines = [l for l in source.splitlines() if l.strip()]
        n_lines.append(len(lines))
        inline_math += source.count('\\(')
        display_math += source.count('\\[') + source.count('$$')
        for m in re.finditer(r'\(\.([\w-]+)', source):
            classes[m.group(1)] += 1
        in_code = False
        for line in lines:
            s = line.strip()
            if in_code:     # content of a code block: not LHTML
                in_code = s != '::'
                continue
            if CODE_OPENER.match(s):
                in_code = True
            m = OPENER.match(s)
            if m:
                tags[m.group(1) or '(bare ::)'] += 1
                if s != '::':
                    openers[s] += 1
            sp = SPACER.match(s)
            if sp:
                spacers[sp.group(1).strip()] += 1
            for st in STYLE.finditer(s):
                for decl in st.group(1).split(';'):
                    if ':' in decl:
                        k, v = (x.strip() for x in decl.split(':', 1))
                        props[k] += 1
                        values[(k, v)] += 1
            head = re.match(r'^(=+|\*+)\s', s)
            if head:
                starts[head.group(1)] += 1
    return {'files': len(n_lines), 'lines_per_slide': lr._median(n_lines) if n_lines else None,
            'tags': tags, 'openers': openers, 'properties': props, 'values': values,
            'spacers': spacers, 'line_starts': starts, 'classes': classes,
            'inline_math': inline_math, 'display_math': display_math}


# ---------------------------------------------------------------------------
# Profile
# ---------------------------------------------------------------------------

def _box_distance(a, b, scale):
    if a is None or b is None:
        return 0 if a is b else 1
    return sum(abs(x - y) for x, y in zip(a, b)) / (4 * scale)


def _median_box(boxes):
    boxes = [b for b in boxes if b]
    return tuple(round(lr._median([b[i] for b in boxes])) for i in range(4)) if boxes else None


def type_profile(slides, area_w):
    """Typical measures of the slides of a type, and its examples: the
    slides closest to the typical measures, without layout problems."""
    f = [s['features'] for s in slides]
    med = lambda k: lr._median([x[k] for x in f])
    typical = {'words': med('words'), 'formulas': med('formulas'), 'code_lines': med('code_lines'),
               'media_items': med('media_items'),
               'text_box': _median_box([x['text_box'] for x in f]),
               'code_box': _median_box([x['code_box'] for x in f]),
               'media_box': _median_box([x['media_box'] for x in f]),
               'fixed_media': round(sum(x['fixed_media'] for x in f) / max(sum(x['media_items'] for x in f), 1), 2)}

    def distance(s):
        x = s['features']
        return (sum(_box_distance(x[k], typical[k], area_w) for k in ('text_box', 'code_box', 'media_box'))
                + abs(x['words'] - typical['words']) / max(typical['words'], 10))

    clean = [s for s in slides if lr.count_problems(s['analysis']) == 0]
    ranked = sorted(clean or slides, key=lambda s: (lr.count_warnings(s['analysis']), distance(s)))
    # examples from different decks first
    examples, seen = [], set()
    for s in ranked:
        if s['page']['deck'] not in seen:
            examples.append(s)
            seen.add(s['page']['deck'])
    examples += [s for s in ranked if s not in examples]
    return typical, examples


def _box_text(box):
    return f'x {box[0]}..{box[2]}, y {box[1]}..{box[3]}' if box else '-'


def _source_excerpt(path, max_lines=40):
    try:
        with open(path, encoding='utf-8', errors='replace') as fid:
            lines = fid.read().strip('\n').splitlines()
    except OSError:
        return '(source not found)'
    if len(lines) > max_lines:
        lines = lines[:max_lines] + [f'... ({len(lines) - max_lines} more lines)']
    return '\n'.join(lines)


def _top(counter, n, fmt=lambda k, v: f'`{k}` ({v})'):
    return ', '.join(fmt(k, v) for k, v in counter.most_common(n))


def style_markdown(decks, slides, types, idioms, n_examples=3):
    total = len(slides)
    lines = ['# Style profile', '',
             f"Measured on {total} slides of {len(decks)} decks: "
             + ', '.join(f"{d} ({n} slides)" for d, n in decks.items()) + '.', '',
             'Coordinates in CSS px on a 1920×1080 slide, origin at the top-left corner.', '',
             'To write a new slide in this style: choose its layout type below, start from the '
             'source of the closest example, keep the usual title, columns, font sizes and density '
             'of the deck, then check it with `generate.py -l --layout`.', '',
             '## Usual values of each deck', '']
    for deck, norms in decks_norms_items(slides):
        lines += [f'### {deck}', '', lr.norms_markdown(norms).split('\n', 2)[2].strip(), '']

    lines += ['## Layout types', '',
              '| type | slides | ' + ' | '.join(decks) + ' | words | description |',
              '|------|--------|' + '|'.join('---' for _ in decks) + '|-------|-------------|']
    for name, t in types.items():
        per_deck = Counter(s['page']['deck'] for s in t['slides'])
        lines.append(f"| {name} | {len(t['slides'])} ({round(100 * len(t['slides']) / total)} %) | "
                     + ' | '.join(str(per_deck.get(d, 0)) for d in decks)
                     + f" | {t['typical']['words']} | {TYPES[name]} |")
    lines.append('')
    for name, t in types.items():
        typ = t['typical']
        lines += [f'### {name}: {TYPES[name]}', '',
                  f"{len(t['slides'])} slides. Typical: {typ['words']} words, {typ['formulas']} formulas, "
                  f"{typ['code_lines']} lines of code, {typ['media_items']} figures "
                  f"({round(100 * typ['fixed_media'])} % of figures placed with position fixed/absolute).",
                  f"Text {_box_text(typ['text_box'])}; code {_box_text(typ['code_box'])}; "
                  f"figures {_box_text(typ['media_box'])}.", '',
                  f"Thumbnails of examples: `types/{name}.png`", '']
        for s in t['examples'][:n_examples]:
            lines += [f"Example `{page_key(s['page'])}` (source `{s['page']['source']}`):", '',
                      '```', _source_excerpt(s['page']['source']), '```', '']

    lines += ['## LHTML idioms (sources)', '',
              f"{idioms['files']} source files, {idioms['lines_per_slide']} non-empty lines per slide (median); "
              f"{idioms['inline_math']} inline formulas `\\( \\)`, {idioms['display_math']} display formulas.", '',
              '- Block tags: ' + _top(idioms['tags'], 12),
              '- Line starts (titles, lists): ' + _top(idioms['line_starts'], 8),
              '- Spacers `div::[height:...]::`: ' + _top(idioms['spacers'], 10),
              '- Style properties: ' + _top(idioms['properties'], 25),
              '- Classes: ' + (_top(idioms['classes'], 10) or 'none'), '',
              'Most used values of the main properties:', '']
    for prop, _ in idioms['properties'].most_common(14):
        values = Counter({v: n for (k, v), n in idioms['values'].items() if k == prop})
        lines.append(f'- `{prop}`: ' + _top(values, 8, lambda k, v: f'`{k}` ({v})'))
    lines += ['', 'Most frequent block openers (lines starting with `tag::` or `::`):', '']
    lines += [f'- `{k}` ({v})' for k, v in idioms['openers'].most_common(30)]
    return '\n'.join(lines) + '\n'


def decks_norms_items(slides):
    by_deck = {}
    for s in slides:
        by_deck.setdefault(s['page']['deck'], []).append(s)
    return [(deck, items[0]['norms']) for deck, items in by_deck.items()]


def write_type_sheets(output_dir, types, n=16):
    os.makedirs(os.path.join(output_dir, 'types'), exist_ok=True)
    sheets = []
    for name, t in types.items():
        rows = [(page_key(s['page']), os.path.relpath(s['page']['out'], os.path.join(output_dir, 'types')),
                 s['analysis']) for s in t['examples'][:n]]
        html = lr.contact_sheets_html(rows, {'w': 1920, 'h': 1080}, columns=4, rows_per_sheet=4)[0]
        path = os.path.abspath(os.path.join(output_dir, 'types', name + '.html'))
        with open(path, 'w', encoding='utf-8') as fid:
            fid.write(html)
        sheets.append({'html': path, 'png': path[:-len('.html')] + '.png'})
    with tempfile.NamedTemporaryFile('w', suffix='.json', delete=False) as fid:
        json.dump(sheets, fid)
    subprocess.run(['node', CONTACT_JS, f'--input={fid.name}'])
    os.remove(fid.name)


def profile(deck_dirs, output_dir, jobs=3, force=False, log=print):
    pages = [p for d in deck_dirs for p in deck_pages(d)]
    measure(pages, output_dir, jobs, force, log)
    by_deck = {}
    for p in pages:
        if os.path.isfile(p['layout_path']):
            with open(p['layout_path'], encoding='utf-8') as fid:
                by_deck.setdefault(p['deck'], []).append((p, json.load(fid)))
    slides, seen, duplicates = [], set(), 0
    for deck, items in by_deck.items():
        norms = lr.deck_norms([layout for _, layout in items])
        for p, layout in items:
            # a slide copied in several chapters counts once
            try:
                with open(p['source'], 'rb') as fid:
                    digest = hashlib.sha1(fid.read()).hexdigest()
            except OSError:
                digest = p['html']
            if digest in seen:
                duplicates += 1
                continue
            seen.add(digest)
            analysis = lr.analyse(layout, norms=norms)
            slides.append({'page': p, 'norms': norms, 'analysis': analysis,
                           'features': slide_features(layout)})
            slides[-1]['type'] = classify(slides[-1]['features'], layout['area'])
    types = {}
    for name in TYPES:
        members = [s for s in slides if s['type'] == name]
        if members:
            typical, examples = type_profile(members, 1920)
            types[name] = {'slides': members, 'typical': typical, 'examples': examples}
    idioms = source_idioms([s['page']['source'] for s in slides])
    decks = dict(Counter(s['page']['deck'] for s in slides))

    os.makedirs(output_dir, exist_ok=True)
    with open(os.path.join(output_dir, 'style.md'), 'w', encoding='utf-8', errors='replace') as fid:
        fid.write(style_markdown(decks, slides, types, idioms))
    data = {'decks': {d: n for d, n in decks.items()},
            'norms': dict(decks_norms_items(slides)),
            'types': {name: {'description': TYPES[name], 'count': len(t['slides']), 'typical': t['typical'],
                             'examples': [page_key(s['page']) for s in t['examples'][:16]]}
                      for name, t in types.items()},
            'slides': [{'page': page_key(s['page']), 'source': s['page']['source'], 'type': s['type'],
                        'features': s['features']} for s in slides],
            'idioms': {k: (v.most_common(60) if isinstance(v, Counter) else v) for k, v in idioms.items()
                       if k != 'values'}}
    with open(os.path.join(output_dir, 'style.json'), 'w') as fid:
        json.dump(data, fid, indent=1, ensure_ascii=False)
    write_type_sheets(output_dir, types)
    log(f"Style profile of {len(slides)} slides ({duplicates} duplicates ignored) -> "
        f"{os.path.join(output_dir, 'style.md')}")
    return types


def main():
    parser = argparse.ArgumentParser(description='Style profile of a corpus of slide decks.')
    parser.add_argument('decks', nargs='+', help='slide projects (with src/ and _site/)')
    parser.add_argument('-o', '--output', default='style/', help='output directory (default: style/)')
    parser.add_argument('-j', '--jobs', type=int, default=3, help='browsers in parallel (default: 3)')
    parser.add_argument('-f', '--force', action='store_true', help='measure again all the pages')
    args = parser.parse_args()
    profile(args.decks, args.output, args.jobs, args.force)


if __name__ == '__main__':
    main()
